//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "state")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub legal_hours: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_state::Entity")]
    UserState,
}

impl Related<super::user_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserState.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
